/* automatically generated by rust-bindgen 0.72.1 */

pub const __CC_SUPPORTS___INLINE: u32 = 1;
pub const __CC_SUPPORTS_SYMVER: u32 = 1;
pub const __POSIX_VISIBLE: u32 = 202405;
pub const __XSI_VISIBLE: u32 = 800;
pub const __BSD_VISIBLE: u32 = 1;
pub const __ISO_C_VISIBLE: u32 = 2023;
pub const __EXT1_VISIBLE: u32 = 1;
pub const __CHAR_BIT: u32 = 8;
pub const __SCHAR_MAX: u32 = 127;
pub const __SCHAR_MIN: i32 = -128;
pub const __UCHAR_MAX: u32 = 255;
pub const __USHRT_MAX: u32 = 65535;
pub const __SHRT_MAX: u32 = 32767;
pub const __SHRT_MIN: i32 = -32768;
pub const __UINT_MAX: u32 = 4294967295;
pub const __INT_MAX: u32 = 2147483647;
pub const __INT_MIN: i32 = -2147483648;
pub const __ULONG_MAX: i32 = -1;
pub const __LONG_MAX: u64 = 9223372036854775807;
pub const __LONG_MIN: i64 = -9223372036854775808;
pub const __ULLONG_MAX: i32 = -1;
pub const __LLONG_MAX: u64 = 9223372036854775807;
pub const __LLONG_MIN: i64 = -9223372036854775808;
pub const __SSIZE_MAX: u64 = 9223372036854775807;
pub const __SIZE_T_MAX: i32 = -1;
pub const __OFF_MAX: u64 = 9223372036854775807;
pub const __OFF_MIN: i64 = -9223372036854775808;
pub const __UQUAD_MAX: i32 = -1;
pub const __QUAD_MAX: u64 = 9223372036854775807;
pub const __QUAD_MIN: i64 = -9223372036854775808;
pub const __LONG_BIT: u32 = 64;
pub const __WORD_BIT: u32 = 32;
pub const __MINSIGSTKSZ: u32 = 2048;
pub const __WCHAR_MIN: i32 = -2147483648;
pub const __WCHAR_MAX: u32 = 2147483647;
pub const _SIG_WORDS: u32 = 4;
pub const _SIG_MAXSIG: u32 = 128;
pub const SS_ONSTACK: u32 = 1;
pub const SS_DISABLE: u32 = 4;
pub const MINSIGSTKSZ: u32 = 2048;
pub const SIGSTKSZ: u32 = 34816;
pub const _X86_SIGNAL_H: u32 = 1;
pub const SIGHUP: u32 = 1;
pub const SIGINT: u32 = 2;
pub const SIGQUIT: u32 = 3;
pub const SIGILL: u32 = 4;
pub const SIGTRAP: u32 = 5;
pub const SIGABRT: u32 = 6;
pub const SIGIOT: u32 = 6;
pub const SIGEMT: u32 = 7;
pub const SIGFPE: u32 = 8;
pub const SIGKILL: u32 = 9;
pub const SIGBUS: u32 = 10;
pub const SIGSEGV: u32 = 11;
pub const SIGSYS: u32 = 12;
pub const SIGPIPE: u32 = 13;
pub const SIGALRM: u32 = 14;
pub const SIGTERM: u32 = 15;
pub const SIGURG: u32 = 16;
pub const SIGSTOP: u32 = 17;
pub const SIGTSTP: u32 = 18;
pub const SIGCONT: u32 = 19;
pub const SIGCHLD: u32 = 20;
pub const SIGTTIN: u32 = 21;
pub const SIGTTOU: u32 = 22;
pub const SIGIO: u32 = 23;
pub const SIGXCPU: u32 = 24;
pub const SIGXFSZ: u32 = 25;
pub const SIGVTALRM: u32 = 26;
pub const SIGPROF: u32 = 27;
pub const SIGWINCH: u32 = 28;
pub const SIGINFO: u32 = 29;
pub const SIGUSR1: u32 = 30;
pub const SIGUSR2: u32 = 31;
pub const SIGTHR: u32 = 32;
pub const SIGLWP: u32 = 32;
pub const SIGLIBRT: u32 = 33;
pub const SIGRTMIN: u32 = 65;
pub const SIGRTMAX: u32 = 126;
pub const SIGEV_NONE: u32 = 0;
pub const SIGEV_SIGNAL: u32 = 1;
pub const SIGEV_THREAD: u32 = 2;
pub const SIGEV_KEVENT: u32 = 3;
pub const SIGEV_THREAD_ID: u32 = 4;
pub const ILL_ILLOPC: u32 = 1;
pub const ILL_ILLOPN: u32 = 2;
pub const ILL_ILLADR: u32 = 3;
pub const ILL_ILLTRP: u32 = 4;
pub const ILL_PRVOPC: u32 = 5;
pub const ILL_PRVREG: u32 = 6;
pub const ILL_COPROC: u32 = 7;
pub const ILL_BADSTK: u32 = 8;
pub const BUS_ADRALN: u32 = 1;
pub const BUS_ADRERR: u32 = 2;
pub const BUS_OBJERR: u32 = 3;
pub const BUS_OOMERR: u32 = 100;
pub const SEGV_MAPERR: u32 = 1;
pub const SEGV_ACCERR: u32 = 2;
pub const SEGV_PKUERR: u32 = 100;
pub const FPE_INTOVF: u32 = 1;
pub const FPE_INTDIV: u32 = 2;
pub const FPE_FLTDIV: u32 = 3;
pub const FPE_FLTOVF: u32 = 4;
pub const FPE_FLTUND: u32 = 5;
pub const FPE_FLTRES: u32 = 6;
pub const FPE_FLTINV: u32 = 7;
pub const FPE_FLTSUB: u32 = 8;
pub const FPE_FLTIDO: u32 = 9;
pub const TRAP_BRKPT: u32 = 1;
pub const TRAP_TRACE: u32 = 2;
pub const TRAP_DTRACE: u32 = 3;
pub const TRAP_CAP: u32 = 4;
pub const CLD_EXITED: u32 = 1;
pub const CLD_KILLED: u32 = 2;
pub const CLD_DUMPED: u32 = 3;
pub const CLD_TRAPPED: u32 = 4;
pub const CLD_STOPPED: u32 = 5;
pub const CLD_CONTINUED: u32 = 6;
pub const POLL_IN: u32 = 1;
pub const POLL_OUT: u32 = 2;
pub const POLL_MSG: u32 = 3;
pub const POLL_ERR: u32 = 4;
pub const POLL_PRI: u32 = 5;
pub const POLL_HUP: u32 = 6;
pub const SA_NOCLDSTOP: u32 = 8;
pub const SA_ONSTACK: u32 = 1;
pub const SA_RESTART: u32 = 2;
pub const SA_RESETHAND: u32 = 4;
pub const SA_NODEFER: u32 = 16;
pub const SA_NOCLDWAIT: u32 = 32;
pub const SA_SIGINFO: u32 = 64;
pub const NSIG: u32 = 32;
pub const SI_NOINFO: u32 = 0;
pub const SI_USER: u32 = 65537;
pub const SI_QUEUE: u32 = 65538;
pub const SI_TIMER: u32 = 65539;
pub const SI_ASYNCIO: u32 = 65540;
pub const SI_MESGQ: u32 = 65541;
pub const SI_KERNEL: u32 = 65542;
pub const SI_LWP: u32 = 65543;
pub const SI_UNDEFINED: u32 = 0;
pub const SV_ONSTACK: u32 = 1;
pub const SV_INTERRUPT: u32 = 2;
pub const SV_RESETHAND: u32 = 4;
pub const SV_NODEFER: u32 = 16;
pub const SV_NOCLDSTOP: u32 = 8;
pub const SV_SIGINFO: u32 = 64;
pub const __SIGQUEUE_TID: u32 = 2147483648;
pub const __SIGQUEUE_RSRV: u32 = 1073741824;
pub const SIG_BLOCK: u32 = 1;
pub const SIG_UNBLOCK: u32 = 2;
pub const SIG_SETMASK: u32 = 3;
pub const NBBY: u32 = 8;
pub const BSD: u32 = 199506;
pub const BSD4_3: u32 = 1;
pub const BSD4_4: u32 = 1;
pub const __FreeBSD_version: u32 = 1500068;
pub const _QUAD_HIGHWORD: u32 = 1;
pub const _QUAD_LOWWORD: u32 = 0;
pub const __SSP_FORTIFY_LEVEL: u32 = 0;
pub const FD_SETSIZE: u32 = 1024;
pub const ARG_MAX: u32 = 524288;
pub const CHILD_MAX: u32 = 40;
pub const MAX_CANON: u32 = 255;
pub const MAX_INPUT: u32 = 255;
pub const NAME_MAX: u32 = 255;
pub const NGROUPS_MAX: u32 = 1023;
pub const OPEN_MAX: u32 = 64;
pub const PATH_MAX: u32 = 1024;
pub const PIPE_BUF: u32 = 512;
pub const IOV_MAX: u32 = 1024;
pub const MAXCOMLEN: u32 = 19;
pub const MAXINTERP: u32 = 1024;
pub const MAXLOGNAME: u32 = 33;
pub const MAXUPRC: u32 = 40;
pub const NCARGS: u32 = 524288;
pub const NGROUPS: u32 = 1024;
pub const NOFILE: u32 = 64;
pub const NOGROUP: u32 = 65535;
pub const MAXHOSTNAMELEN: u32 = 256;
pub const SPECNAMELEN: u32 = 255;
pub const MACHINE: &[u8; 6] = b"amd64\0";
pub const MACHINE_ARCH: &[u8; 6] = b"amd64\0";
pub const MACHINE_ARCH32: &[u8; 5] = b"i386\0";
pub const MAXCPU: u32 = 1;
pub const MAXMEMDOM: u32 = 8;
pub const CACHE_LINE_SHIFT: u32 = 6;
pub const CACHE_LINE_SIZE: u32 = 64;
pub const NPTEPGSHIFT: u32 = 9;
pub const PAGE_SHIFT: u32 = 12;
pub const PAGE_SIZE: u32 = 4096;
pub const PAGE_MASK: u32 = 4095;
pub const NPDEPGSHIFT: u32 = 9;
pub const PDRSHIFT: u32 = 21;
pub const NBPDR: u32 = 2097152;
pub const PDRMASK: u32 = 2097151;
pub const NPDPEPGSHIFT: u32 = 9;
pub const PDPSHIFT: u32 = 30;
pub const NBPDP: u32 = 1073741824;
pub const PDPMASK: u32 = 1073741823;
pub const NPML4EPGSHIFT: u32 = 9;
pub const PML4SHIFT: u32 = 39;
pub const NBPML4: u64 = 549755813888;
pub const PML4MASK: u64 = 549755813887;
pub const NPML5EPGSHIFT: u32 = 9;
pub const PML5SHIFT: u32 = 48;
pub const NBPML5: u64 = 281474976710656;
pub const PML5MASK: u64 = 281474976710655;
pub const MAXPAGESIZES: u32 = 3;
pub const IOPAGES: u32 = 2;
pub const IOPERM_BITMAP_SIZE: u32 = 8193;
pub const KSTACK_PAGES: u32 = 4;
pub const KSTACK_GUARD_PAGES: u32 = 1;
pub const SC_TABLESIZE: u32 = 1024;
pub const CHAR_BIT: u32 = 8;
pub const SCHAR_MAX: u32 = 127;
pub const SCHAR_MIN: i32 = -128;
pub const UCHAR_MAX: u32 = 255;
pub const CHAR_MAX: u32 = 127;
pub const CHAR_MIN: i32 = -128;
pub const USHRT_MAX: u32 = 65535;
pub const SHRT_MAX: u32 = 32767;
pub const SHRT_MIN: i32 = -32768;
pub const UINT_MAX: u32 = 4294967295;
pub const INT_MAX: u32 = 2147483647;
pub const INT_MIN: i32 = -2147483648;
pub const ULONG_MAX: i32 = -1;
pub const LONG_MAX: u64 = 9223372036854775807;
pub const LONG_MIN: i64 = -9223372036854775808;
pub const ULLONG_MAX: i32 = -1;
pub const LLONG_MAX: u64 = 9223372036854775807;
pub const LLONG_MIN: i64 = -9223372036854775808;
pub const SSIZE_MAX: u64 = 9223372036854775807;
pub const SIZE_T_MAX: i32 = -1;
pub const OFF_MAX: u64 = 9223372036854775807;
pub const OFF_MIN: i64 = -9223372036854775808;
pub const GID_MAX: u32 = 4294967295;
pub const UID_MAX: u32 = 4294967295;
pub const UQUAD_MAX: i32 = -1;
pub const QUAD_MAX: u64 = 9223372036854775807;
pub const QUAD_MIN: i64 = -9223372036854775808;
pub const LONG_BIT: u32 = 64;
pub const WORD_BIT: u32 = 32;
pub const MQ_PRIO_MAX: u32 = 64;
pub const MAXPHYS: u32 = 1048576;
pub const DEV_BSHIFT: u32 = 9;
pub const DEV_BSIZE: u32 = 512;
pub const BLKDEV_IOSIZE: u32 = 4096;
pub const DFLTPHYS: u32 = 65536;
pub const MAXDUMPPGS: u32 = 16;
pub const MSIZE: u32 = 256;
pub const MCLSHIFT: u32 = 11;
pub const MCLBYTES: u32 = 2048;
pub const MJUMPAGESIZE: u32 = 4096;
pub const MJUM9BYTES: u32 = 9216;
pub const MJUM16BYTES: u32 = 16384;
pub const PRIMASK: u32 = 255;
pub const PCATCH: u32 = 256;
pub const PDROP: u32 = 512;
pub const PNOLOCK: u32 = 1024;
pub const PRILASTFLAG: u32 = 1024;
pub const NZERO: u32 = 0;
pub const CMASK: u32 = 18;
pub const MAXBSIZE: u32 = 65536;
pub const MAXBCACHEBUF: u32 = 65536;
pub const BKVASIZE: u32 = 16384;
pub const BKVAMASK: u32 = 16383;
pub const MAXPATHLEN: u32 = 1024;
pub const MAXSYMLINKS: u32 = 32;
pub const FSHIFT: u32 = 11;
pub const FSCALE: u32 = 2048;
pub const DBREG_DR6_RESERVED1: u32 = 4294905840;
pub const DBREG_DR6_BMASK: u32 = 15;
pub const DBREG_DR6_BD: u32 = 8192;
pub const DBREG_DR6_BS: u32 = 16384;
pub const DBREG_DR6_BT: u32 = 32768;
pub const DBREG_DR7_RESERVED1: u32 = 1024;
pub const DBREG_DR7_LOCAL_ENABLE: u32 = 1;
pub const DBREG_DR7_GLOBAL_ENABLE: u32 = 2;
pub const DBREG_DR7_LEN_1: u32 = 0;
pub const DBREG_DR7_LEN_2: u32 = 1;
pub const DBREG_DR7_LEN_4: u32 = 3;
pub const DBREG_DR7_LEN_8: u32 = 2;
pub const DBREG_DR7_EXEC: u32 = 0;
pub const DBREG_DR7_WRONLY: u32 = 1;
pub const DBREG_DR7_RDWR: u32 = 3;
pub const DBREG_DR7_GD: u32 = 8192;
pub const PT_TRACE_ME: u32 = 0;
pub const PT_READ_I: u32 = 1;
pub const PT_READ_D: u32 = 2;
pub const PT_WRITE_I: u32 = 4;
pub const PT_WRITE_D: u32 = 5;
pub const PT_CONTINUE: u32 = 7;
pub const PT_KILL: u32 = 8;
pub const PT_STEP: u32 = 9;
pub const PT_ATTACH: u32 = 10;
pub const PT_DETACH: u32 = 11;
pub const PT_IO: u32 = 12;
pub const PT_LWPINFO: u32 = 13;
pub const PT_GETNUMLWPS: u32 = 14;
pub const PT_GETLWPLIST: u32 = 15;
pub const PT_CLEARSTEP: u32 = 16;
pub const PT_SETSTEP: u32 = 17;
pub const PT_SUSPEND: u32 = 18;
pub const PT_RESUME: u32 = 19;
pub const PT_TO_SCE: u32 = 20;
pub const PT_TO_SCX: u32 = 21;
pub const PT_SYSCALL: u32 = 22;
pub const PT_FOLLOW_FORK: u32 = 23;
pub const PT_LWP_EVENTS: u32 = 24;
pub const PT_GET_EVENT_MASK: u32 = 25;
pub const PT_SET_EVENT_MASK: u32 = 26;
pub const PT_GET_SC_ARGS: u32 = 27;
pub const PT_GET_SC_RET: u32 = 28;
pub const PT_COREDUMP: u32 = 29;
pub const PT_GETREGS: u32 = 33;
pub const PT_SETREGS: u32 = 34;
pub const PT_GETFPREGS: u32 = 35;
pub const PT_SETFPREGS: u32 = 36;
pub const PT_GETDBREGS: u32 = 37;
pub const PT_SETDBREGS: u32 = 38;
pub const PT_VM_TIMESTAMP: u32 = 40;
pub const PT_VM_ENTRY: u32 = 41;
pub const PT_GETREGSET: u32 = 42;
pub const PT_SETREGSET: u32 = 43;
pub const PT_SC_REMOTE: u32 = 44;
pub const PT_FIRSTMACH: u32 = 64;
pub const PT_LASTMACH: u32 = 127;
pub const PT_GETXSTATE_INFO: u32 = 68;
pub const PT_GETXSTATE: u32 = 69;
pub const PT_SETXSTATE: u32 = 70;
pub const PT_GETFSBASE: u32 = 71;
pub const PT_SETFSBASE: u32 = 72;
pub const PT_GETGSBASE: u32 = 73;
pub const PT_SETGSBASE: u32 = 74;
pub const PT_GETTLSBASE: u32 = 75;
pub const PT_SETTLSBASE: u32 = 76;
pub const PTRACE_EXEC: u32 = 1;
pub const PTRACE_SCE: u32 = 2;
pub const PTRACE_SCX: u32 = 4;
pub const PTRACE_SYSCALL: u32 = 6;
pub const PTRACE_FORK: u32 = 8;
pub const PTRACE_LWP: u32 = 16;
pub const PTRACE_VFORK: u32 = 32;
pub const PTRACE_DEFAULT: u32 = 1;
pub const PIOD_READ_D: u32 = 1;
pub const PIOD_WRITE_D: u32 = 2;
pub const PIOD_READ_I: u32 = 3;
pub const PIOD_WRITE_I: u32 = 4;
pub const PL_EVENT_NONE: u32 = 0;
pub const PL_EVENT_SIGNAL: u32 = 1;
pub const PL_FLAG_SA: u32 = 1;
pub const PL_FLAG_BOUND: u32 = 2;
pub const PL_FLAG_SCE: u32 = 4;
pub const PL_FLAG_SCX: u32 = 8;
pub const PL_FLAG_EXEC: u32 = 16;
pub const PL_FLAG_SI: u32 = 32;
pub const PL_FLAG_FORKED: u32 = 64;
pub const PL_FLAG_CHILD: u32 = 128;
pub const PL_FLAG_BORN: u32 = 256;
pub const PL_FLAG_EXITED: u32 = 512;
pub const PL_FLAG_VFORKED: u32 = 1024;
pub const PL_FLAG_VFORK_DONE: u32 = 2048;
pub const PC_COMPRESS: u32 = 1;
pub const PC_ALL: u32 = 2;
pub type __int8_t = ::std::os::raw::c_schar;
pub type __uint8_t = ::std::os::raw::c_uchar;
pub type __int16_t = ::std::os::raw::c_short;
pub type __uint16_t = ::std::os::raw::c_ushort;
pub type __int32_t = ::std::os::raw::c_int;
pub type __uint32_t = ::std::os::raw::c_uint;
pub type __int64_t = ::std::os::raw::c_long;
pub type __uint64_t = ::std::os::raw::c_ulong;
pub type __int_least8_t = __int8_t;
pub type __int_least16_t = __int16_t;
pub type __int_least32_t = __int32_t;
pub type __int_least64_t = __int64_t;
pub type __intmax_t = __int64_t;
pub type __uint_least8_t = __uint8_t;
pub type __uint_least16_t = __uint16_t;
pub type __uint_least32_t = __uint32_t;
pub type __uint_least64_t = __uint64_t;
pub type __uintmax_t = __uint64_t;
pub type __intptr_t = __int64_t;
pub type __intfptr_t = __int64_t;
pub type __uintptr_t = __uint64_t;
pub type __uintfptr_t = __uint64_t;
pub type __vm_offset_t = __uint64_t;
pub type __vm_size_t = __uint64_t;
pub type __size_t = __uint64_t;
pub type __ssize_t = __int64_t;
pub type __ptrdiff_t = __int64_t;
pub type __clock_t = __int32_t;
pub type __critical_t = __int64_t;
pub type __double_t = f64;
pub type __float_t = f32;
pub type __int_fast8_t = __int32_t;
pub type __int_fast16_t = __int32_t;
pub type __int_fast32_t = __int32_t;
pub type __int_fast64_t = __int64_t;
pub type __register_t = __int64_t;
pub type __segsz_t = __int64_t;
pub type __time_t = __int64_t;
pub type __uint_fast8_t = __uint32_t;
pub type __uint_fast16_t = __uint32_t;
pub type __uint_fast32_t = __uint32_t;
pub type __uint_fast64_t = __uint64_t;
pub type __u_register_t = __uint64_t;
pub type __vm_paddr_t = __uint64_t;
pub type ___wchar_t = ::std::os::raw::c_int;
pub type __blksize_t = __int32_t;
pub type __blkcnt_t = __int64_t;
pub type __clockid_t = __int32_t;
pub type __fflags_t = __uint32_t;
pub type __fsblkcnt_t = __uint64_t;
pub type __fsfilcnt_t = __uint64_t;
pub type __gid_t = __uint32_t;
pub type __id_t = __int64_t;
pub type __ino_t = __uint64_t;
pub type __key_t = ::std::os::raw::c_long;
pub type __lwpid_t = __int32_t;
pub type __mode_t = __uint16_t;
pub type __accmode_t = ::std::os::raw::c_int;
pub type __nl_item = ::std::os::raw::c_int;
pub type __nlink_t = __uint64_t;
pub type __off_t = __int64_t;
pub type __off64_t = __int64_t;
pub type __pid_t = __int32_t;
pub type __sbintime_t = __int64_t;
pub type __rlim_t = __int64_t;
pub type __sa_family_t = __uint8_t;
pub type __socklen_t = __uint32_t;
pub type __suseconds_t = ::std::os::raw::c_long;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __timer {
    _unused: [u8; 0],
}
pub type __timer_t = *mut __timer;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __mq {
    _unused: [u8; 0],
}
pub type __mqd_t = *mut __mq;
pub type __uid_t = __uint32_t;
pub type __useconds_t = ::std::os::raw::c_uint;
pub type __cpuwhich_t = ::std::os::raw::c_int;
pub type __cpulevel_t = ::std::os::raw::c_int;
pub type __cpusetid_t = ::std::os::raw::c_int;
pub type __daddr_t = __int64_t;
pub type __ct_rune_t = ::std::os::raw::c_int;
pub type __rune_t = __ct_rune_t;
pub type __wint_t = __ct_rune_t;
pub type __char16_t = __uint_least16_t;
pub type __char32_t = __uint_least32_t;
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct __max_align_t {
    pub __max_align1: ::std::os::raw::c_longlong,
    pub __bindgen_padding_0: u64,
    pub __max_align2: u128,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __max_align_t"][::std::mem::size_of::<__max_align_t>() - 32usize];
    ["Alignment of __max_align_t"][::std::mem::align_of::<__max_align_t>() - 16usize];
    ["Offset of field: __max_align_t::__max_align1"]
        [::std::mem::offset_of!(__max_align_t, __max_align1) - 0usize];
    ["Offset of field: __max_align_t::__max_align2"]
        [::std::mem::offset_of!(__max_align_t, __max_align2) - 16usize];
};
pub type __acl_tag_t = __uint32_t;
pub type __acl_perm_t = __uint32_t;
pub type __acl_entry_type_t = __uint16_t;
pub type __acl_flag_t = __uint16_t;
pub type __acl_type_t = __uint32_t;
pub type __acl_permset_t = *mut __uint32_t;
pub type __acl_flagset_t = *mut __uint16_t;
pub type __dev_t = __uint64_t;
pub type __fixpt_t = __uint32_t;
#[repr(C)]
#[derive(Copy, Clone)]
pub union __mbstate_t {
    pub __mbstate8: [::std::os::raw::c_char; 128usize],
    pub _mbstateL: __int64_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __mbstate_t"][::std::mem::size_of::<__mbstate_t>() - 128usize];
    ["Alignment of __mbstate_t"][::std::mem::align_of::<__mbstate_t>() - 8usize];
    ["Offset of field: __mbstate_t::__mbstate8"]
        [::std::mem::offset_of!(__mbstate_t, __mbstate8) - 0usize];
    ["Offset of field: __mbstate_t::_mbstateL"]
        [::std::mem::offset_of!(__mbstate_t, _mbstateL) - 0usize];
};
pub type __rman_res_t = __uintmax_t;
pub type __va_list = __builtin_va_list;
pub type __gnuc_va_list = __va_list;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __sigset {
    pub __bits: [__uint32_t; 4usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __sigset"][::std::mem::size_of::<__sigset>() - 16usize];
    ["Alignment of __sigset"][::std::mem::align_of::<__sigset>() - 4usize];
    ["Offset of field: __sigset::__bits"][::std::mem::offset_of!(__sigset, __bits) - 0usize];
};
pub type __sigset_t = __sigset;
pub type stack_t = sigaltstack;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sigaltstack {
    pub ss_sp: *mut ::std::os::raw::c_void,
    pub ss_size: __size_t,
    pub ss_flags: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of sigaltstack"][::std::mem::size_of::<sigaltstack>() - 24usize];
    ["Alignment of sigaltstack"][::std::mem::align_of::<sigaltstack>() - 8usize];
    ["Offset of field: sigaltstack::ss_sp"][::std::mem::offset_of!(sigaltstack, ss_sp) - 0usize];
    ["Offset of field: sigaltstack::ss_size"]
        [::std::mem::offset_of!(sigaltstack, ss_size) - 8usize];
    ["Offset of field: sigaltstack::ss_flags"]
        [::std::mem::offset_of!(sigaltstack, ss_flags) - 16usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub union sigval {
    pub sival_int: ::std::os::raw::c_int,
    pub sival_ptr: *mut ::std::os::raw::c_void,
    pub sigval_int: ::std::os::raw::c_int,
    pub sigval_ptr: *mut ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of sigval"][::std::mem::size_of::<sigval>() - 8usize];
    ["Alignment of sigval"][::std::mem::align_of::<sigval>() - 8usize];
    ["Offset of field: sigval::sival_int"][::std::mem::offset_of!(sigval, sival_int) - 0usize];
    ["Offset of field: sigval::sival_ptr"][::std::mem::offset_of!(sigval, sival_ptr) - 0usize];
    ["Offset of field: sigval::sigval_int"][::std::mem::offset_of!(sigval, sigval_int) - 0usize];
    ["Offset of field: sigval::sigval_ptr"][::std::mem::offset_of!(sigval, sigval_ptr) - 0usize];
};
pub type sig_atomic_t = ::std::os::raw::c_long;
#[repr(C)]
#[repr(align(16))]
#[derive(Debug, Copy, Clone)]
pub struct sigcontext {
    pub sc_mask: __sigset,
    pub sc_onstack: ::std::os::raw::c_long,
    pub sc_rdi: ::std::os::raw::c_long,
    pub sc_rsi: ::std::os::raw::c_long,
    pub sc_rdx: ::std::os::raw::c_long,
    pub sc_rcx: ::std::os::raw::c_long,
    pub sc_r8: ::std::os::raw::c_long,
    pub sc_r9: ::std::os::raw::c_long,
    pub sc_rax: ::std::os::raw::c_long,
    pub sc_rbx: ::std::os::raw::c_long,
    pub sc_rbp: ::std::os::raw::c_long,
    pub sc_r10: ::std::os::raw::c_long,
    pub sc_r11: ::std::os::raw::c_long,
    pub sc_r12: ::std::os::raw::c_long,
    pub sc_r13: ::std::os::raw::c_long,
    pub sc_r14: ::std::os::raw::c_long,
    pub sc_r15: ::std::os::raw::c_long,
    pub sc_trapno: ::std::os::raw::c_int,
    pub sc_fs: ::std::os::raw::c_short,
    pub sc_gs: ::std::os::raw::c_short,
    pub sc_addr: ::std::os::raw::c_long,
    pub sc_flags: ::std::os::raw::c_int,
    pub sc_es: ::std::os::raw::c_short,
    pub sc_ds: ::std::os::raw::c_short,
    pub sc_err: ::std::os::raw::c_long,
    pub sc_rip: ::std::os::raw::c_long,
    pub sc_cs: ::std::os::raw::c_long,
    pub sc_rflags: ::std::os::raw::c_long,
    pub sc_rsp: ::std::os::raw::c_long,
    pub sc_ss: ::std::os::raw::c_long,
    pub sc_len: ::std::os::raw::c_long,
    pub sc_fpformat: ::std::os::raw::c_long,
    pub sc_ownedfp: ::std::os::raw::c_long,
    pub sc_fpstate: [::std::os::raw::c_long; 64usize],
    pub sc_fsbase: ::std::os::raw::c_long,
    pub sc_gsbase: ::std::os::raw::c_long,
    pub sc_xfpustate: ::std::os::raw::c_long,
    pub sc_xfpustate_len: ::std::os::raw::c_long,
    pub sc_spare: [::std::os::raw::c_long; 4usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of sigcontext"][::std::mem::size_of::<sigcontext>() - 816usize];
    ["Alignment of sigcontext"][::std::mem::align_of::<sigcontext>() - 16usize];
    ["Offset of field: sigcontext::sc_mask"][::std::mem::offset_of!(sigcontext, sc_mask) - 0usize];
    ["Offset of field: sigcontext::sc_onstack"]
        [::std::mem::offset_of!(sigcontext, sc_onstack) - 16usize];
    ["Offset of field: sigcontext::sc_rdi"][::std::mem::offset_of!(sigcontext, sc_rdi) - 24usize];
    ["Offset of field: sigcontext::sc_rsi"][::std::mem::offset_of!(sigcontext, sc_rsi) - 32usize];
    ["Offset of field: sigcontext::sc_rdx"][::std::mem::offset_of!(sigcontext, sc_rdx) - 40usize];
    ["Offset of field: sigcontext::sc_rcx"][::std::mem::offset_of!(sigcontext, sc_rcx) - 48usize];
    ["Offset of field: sigcontext::sc_r8"][::std::mem::offset_of!(sigcontext, sc_r8) - 56usize];
    ["Offset of field: sigcontext::sc_r9"][::std::mem::offset_of!(sigcontext, sc_r9) - 64usize];
    ["Offset of field: sigcontext::sc_rax"][::std::mem::offset_of!(sigcontext, sc_rax) - 72usize];
    ["Offset of field: sigcontext::sc_rbx"][::std::mem::offset_of!(sigcontext, sc_rbx) - 80usize];
    ["Offset of field: sigcontext::sc_rbp"][::std::mem::offset_of!(sigcontext, sc_rbp) - 88usize];
    ["Offset of field: sigcontext::sc_r10"][::std::mem::offset_of!(sigcontext, sc_r10) - 96usize];
    ["Offset of field: sigcontext::sc_r11"][::std::mem::offset_of!(sigcontext, sc_r11) - 104usize];
    ["Offset of field: sigcontext::sc_r12"][::std::mem::offset_of!(sigcontext, sc_r12) - 112usize];
    ["Offset of field: sigcontext::sc_r13"][::std::mem::offset_of!(sigcontext, sc_r13) - 120usize];
    ["Offset of field: sigcontext::sc_r14"][::std::mem::offset_of!(sigcontext, sc_r14) - 128usize];
    ["Offset of field: sigcontext::sc_r15"][::std::mem::offset_of!(sigcontext, sc_r15) - 136usize];
    ["Offset of field: sigcontext::sc_trapno"]
        [::std::mem::offset_of!(sigcontext, sc_trapno) - 144usize];
    ["Offset of field: sigcontext::sc_fs"][::std::mem::offset_of!(sigcontext, sc_fs) - 148usize];
    ["Offset of field: sigcontext::sc_gs"][::std::mem::offset_of!(sigcontext, sc_gs) - 150usize];
    ["Offset of field: sigcontext::sc_addr"]
        [::std::mem::offset_of!(sigcontext, sc_addr) - 152usize];
    ["Offset of field: sigcontext::sc_flags"]
        [::std::mem::offset_of!(sigcontext, sc_flags) - 160usize];
    ["Offset of field: sigcontext::sc_es"][::std::mem::offset_of!(sigcontext, sc_es) - 164usize];
    ["Offset of field: sigcontext::sc_ds"][::std::mem::offset_of!(sigcontext, sc_ds) - 166usize];
    ["Offset of field: sigcontext::sc_err"][::std::mem::offset_of!(sigcontext, sc_err) - 168usize];
    ["Offset of field: sigcontext::sc_rip"][::std::mem::offset_of!(sigcontext, sc_rip) - 176usize];
    ["Offset of field: sigcontext::sc_cs"][::std::mem::offset_of!(sigcontext, sc_cs) - 184usize];
    ["Offset of field: sigcontext::sc_rflags"]
        [::std::mem::offset_of!(sigcontext, sc_rflags) - 192usize];
    ["Offset of field: sigcontext::sc_rsp"][::std::mem::offset_of!(sigcontext, sc_rsp) - 200usize];
    ["Offset of field: sigcontext::sc_ss"][::std::mem::offset_of!(sigcontext, sc_ss) - 208usize];
    ["Offset of field: sigcontext::sc_len"][::std::mem::offset_of!(sigcontext, sc_len) - 216usize];
    ["Offset of field: sigcontext::sc_fpformat"]
        [::std::mem::offset_of!(sigcontext, sc_fpformat) - 224usize];
    ["Offset of field: sigcontext::sc_ownedfp"]
        [::std::mem::offset_of!(sigcontext, sc_ownedfp) - 232usize];
    ["Offset of field: sigcontext::sc_fpstate"]
        [::std::mem::offset_of!(sigcontext, sc_fpstate) - 240usize];
    ["Offset of field: sigcontext::sc_fsbase"]
        [::std::mem::offset_of!(sigcontext, sc_fsbase) - 752usize];
    ["Offset of field: sigcontext::sc_gsbase"]
        [::std::mem::offset_of!(sigcontext, sc_gsbase) - 760usize];
    ["Offset of field: sigcontext::sc_xfpustate"]
        [::std::mem::offset_of!(sigcontext, sc_xfpustate) - 768usize];
    ["Offset of field: sigcontext::sc_xfpustate_len"]
        [::std::mem::offset_of!(sigcontext, sc_xfpustate_len) - 776usize];
    ["Offset of field: sigcontext::sc_spare"]
        [::std::mem::offset_of!(sigcontext, sc_spare) - 784usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pthread {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pthread_attr {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pthread_cond {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pthread_cond_attr {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pthread_mutex {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pthread_mutex_attr {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pthread_rwlock {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pthread_rwlockattr {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pthread_barrier {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pthread_barrier_attr {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pthread_spinlock {
    _unused: [u8; 0],
}
pub type pthread_t = *mut pthread;
pub type pthread_attr_t = *mut pthread_attr;
pub type pthread_mutex_t = *mut pthread_mutex;
pub type pthread_mutexattr_t = *mut pthread_mutex_attr;
pub type pthread_cond_t = *mut pthread_cond;
pub type pthread_condattr_t = *mut pthread_cond_attr;
pub type pthread_key_t = ::std::os::raw::c_int;
pub type pthread_once_t = pthread_once;
pub type pthread_rwlock_t = *mut pthread_rwlock;
pub type pthread_rwlockattr_t = *mut pthread_rwlockattr;
pub type pthread_barrier_t = *mut pthread_barrier;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pthread_barrierattr {
    _unused: [u8; 0],
}
pub type pthread_barrierattr_t = *mut pthread_barrierattr;
pub type pthread_spinlock_t = *mut pthread_spinlock;
pub type pthread_addr_t = *mut ::std::os::raw::c_void;
pub type pthread_startroutine_t = ::std::option::Option<
    unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void) -> *mut ::std::os::raw::c_void,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pthread_once {
    pub state: ::std::os::raw::c_int,
    pub mutex: pthread_mutex_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of pthread_once"][::std::mem::size_of::<pthread_once>() - 16usize];
    ["Alignment of pthread_once"][::std::mem::align_of::<pthread_once>() - 8usize];
    ["Offset of field: pthread_once::state"][::std::mem::offset_of!(pthread_once, state) - 0usize];
    ["Offset of field: pthread_once::mutex"][::std::mem::offset_of!(pthread_once, mutex) - 8usize];
};
pub type time_t = __time_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct timespec {
    pub tv_sec: time_t,
    pub tv_nsec: ::std::os::raw::c_long,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of timespec"][::std::mem::size_of::<timespec>() - 16usize];
    ["Alignment of timespec"][::std::mem::align_of::<timespec>() - 8usize];
    ["Offset of field: timespec::tv_sec"][::std::mem::offset_of!(timespec, tv_sec) - 0usize];
    ["Offset of field: timespec::tv_nsec"][::std::mem::offset_of!(timespec, tv_nsec) - 8usize];
};
pub type uid_t = __uid_t;
pub type __sighandler_t = ::std::option::Option<unsafe extern "C" fn(arg1: ::std::os::raw::c_int)>;
pub type sigset_t = __sigset_t;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct sigevent {
    pub sigev_notify: ::std::os::raw::c_int,
    pub sigev_signo: ::std::os::raw::c_int,
    pub sigev_value: sigval,
    pub _sigev_un: sigevent__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union sigevent__bindgen_ty_1 {
    pub _threadid: __lwpid_t,
    pub _sigev_thread: sigevent__bindgen_ty_1__bindgen_ty_1,
    pub _kevent_flags: ::std::os::raw::c_ushort,
    pub __spare__: [::std::os::raw::c_long; 8usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sigevent__bindgen_ty_1__bindgen_ty_1 {
    pub _function: ::std::option::Option<unsafe extern "C" fn(arg1: sigval)>,
    pub _attribute: *mut *mut pthread_attr,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of sigevent__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::size_of::<sigevent__bindgen_ty_1__bindgen_ty_1>() - 16usize];
    ["Alignment of sigevent__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::align_of::<sigevent__bindgen_ty_1__bindgen_ty_1>() - 8usize];
    ["Offset of field: sigevent__bindgen_ty_1__bindgen_ty_1::_function"]
        [::std::mem::offset_of!(sigevent__bindgen_ty_1__bindgen_ty_1, _function) - 0usize];
    ["Offset of field: sigevent__bindgen_ty_1__bindgen_ty_1::_attribute"]
        [::std::mem::offset_of!(sigevent__bindgen_ty_1__bindgen_ty_1, _attribute) - 8usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of sigevent__bindgen_ty_1"][::std::mem::size_of::<sigevent__bindgen_ty_1>() - 64usize];
    ["Alignment of sigevent__bindgen_ty_1"]
        [::std::mem::align_of::<sigevent__bindgen_ty_1>() - 8usize];
    ["Offset of field: sigevent__bindgen_ty_1::_threadid"]
        [::std::mem::offset_of!(sigevent__bindgen_ty_1, _threadid) - 0usize];
    ["Offset of field: sigevent__bindgen_ty_1::_sigev_thread"]
        [::std::mem::offset_of!(sigevent__bindgen_ty_1, _sigev_thread) - 0usize];
    ["Offset of field: sigevent__bindgen_ty_1::_kevent_flags"]
        [::std::mem::offset_of!(sigevent__bindgen_ty_1, _kevent_flags) - 0usize];
    ["Offset of field: sigevent__bindgen_ty_1::__spare__"]
        [::std::mem::offset_of!(sigevent__bindgen_ty_1, __spare__) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of sigevent"][::std::mem::size_of::<sigevent>() - 80usize];
    ["Alignment of sigevent"][::std::mem::align_of::<sigevent>() - 8usize];
    ["Offset of field: sigevent::sigev_notify"]
        [::std::mem::offset_of!(sigevent, sigev_notify) - 0usize];
    ["Offset of field: sigevent::sigev_signo"]
        [::std::mem::offset_of!(sigevent, sigev_signo) - 4usize];
    ["Offset of field: sigevent::sigev_value"]
        [::std::mem::offset_of!(sigevent, sigev_value) - 8usize];
    ["Offset of field: sigevent::_sigev_un"][::std::mem::offset_of!(sigevent, _sigev_un) - 16usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct __siginfo {
    pub si_signo: ::std::os::raw::c_int,
    pub si_errno: ::std::os::raw::c_int,
    pub si_code: ::std::os::raw::c_int,
    pub si_pid: __pid_t,
    pub si_uid: __uid_t,
    pub si_status: ::std::os::raw::c_int,
    pub si_addr: *mut ::std::os::raw::c_void,
    pub si_value: sigval,
    pub _reason: __siginfo__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union __siginfo__bindgen_ty_1 {
    pub _fault: __siginfo__bindgen_ty_1__bindgen_ty_1,
    pub _timer: __siginfo__bindgen_ty_1__bindgen_ty_2,
    pub _mesgq: __siginfo__bindgen_ty_1__bindgen_ty_3,
    pub _poll: __siginfo__bindgen_ty_1__bindgen_ty_4,
    pub _capsicum: __siginfo__bindgen_ty_1__bindgen_ty_5,
    pub __spare__: __siginfo__bindgen_ty_1__bindgen_ty_6,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __siginfo__bindgen_ty_1__bindgen_ty_1 {
    pub _trapno: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __siginfo__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::size_of::<__siginfo__bindgen_ty_1__bindgen_ty_1>() - 4usize];
    ["Alignment of __siginfo__bindgen_ty_1__bindgen_ty_1"]
        [::std::mem::align_of::<__siginfo__bindgen_ty_1__bindgen_ty_1>() - 4usize];
    ["Offset of field: __siginfo__bindgen_ty_1__bindgen_ty_1::_trapno"]
        [::std::mem::offset_of!(__siginfo__bindgen_ty_1__bindgen_ty_1, _trapno) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __siginfo__bindgen_ty_1__bindgen_ty_2 {
    pub _timerid: ::std::os::raw::c_int,
    pub _overrun: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __siginfo__bindgen_ty_1__bindgen_ty_2"]
        [::std::mem::size_of::<__siginfo__bindgen_ty_1__bindgen_ty_2>() - 8usize];
    ["Alignment of __siginfo__bindgen_ty_1__bindgen_ty_2"]
        [::std::mem::align_of::<__siginfo__bindgen_ty_1__bindgen_ty_2>() - 4usize];
    ["Offset of field: __siginfo__bindgen_ty_1__bindgen_ty_2::_timerid"]
        [::std::mem::offset_of!(__siginfo__bindgen_ty_1__bindgen_ty_2, _timerid) - 0usize];
    ["Offset of field: __siginfo__bindgen_ty_1__bindgen_ty_2::_overrun"]
        [::std::mem::offset_of!(__siginfo__bindgen_ty_1__bindgen_ty_2, _overrun) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __siginfo__bindgen_ty_1__bindgen_ty_3 {
    pub _mqd: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __siginfo__bindgen_ty_1__bindgen_ty_3"]
        [::std::mem::size_of::<__siginfo__bindgen_ty_1__bindgen_ty_3>() - 4usize];
    ["Alignment of __siginfo__bindgen_ty_1__bindgen_ty_3"]
        [::std::mem::align_of::<__siginfo__bindgen_ty_1__bindgen_ty_3>() - 4usize];
    ["Offset of field: __siginfo__bindgen_ty_1__bindgen_ty_3::_mqd"]
        [::std::mem::offset_of!(__siginfo__bindgen_ty_1__bindgen_ty_3, _mqd) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __siginfo__bindgen_ty_1__bindgen_ty_4 {
    pub _band: ::std::os::raw::c_long,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __siginfo__bindgen_ty_1__bindgen_ty_4"]
        [::std::mem::size_of::<__siginfo__bindgen_ty_1__bindgen_ty_4>() - 8usize];
    ["Alignment of __siginfo__bindgen_ty_1__bindgen_ty_4"]
        [::std::mem::align_of::<__siginfo__bindgen_ty_1__bindgen_ty_4>() - 8usize];
    ["Offset of field: __siginfo__bindgen_ty_1__bindgen_ty_4::_band"]
        [::std::mem::offset_of!(__siginfo__bindgen_ty_1__bindgen_ty_4, _band) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __siginfo__bindgen_ty_1__bindgen_ty_5 {
    pub _syscall: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __siginfo__bindgen_ty_1__bindgen_ty_5"]
        [::std::mem::size_of::<__siginfo__bindgen_ty_1__bindgen_ty_5>() - 4usize];
    ["Alignment of __siginfo__bindgen_ty_1__bindgen_ty_5"]
        [::std::mem::align_of::<__siginfo__bindgen_ty_1__bindgen_ty_5>() - 4usize];
    ["Offset of field: __siginfo__bindgen_ty_1__bindgen_ty_5::_syscall"]
        [::std::mem::offset_of!(__siginfo__bindgen_ty_1__bindgen_ty_5, _syscall) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __siginfo__bindgen_ty_1__bindgen_ty_6 {
    pub __spare1__: ::std::os::raw::c_long,
    pub __spare2__: [::std::os::raw::c_int; 7usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __siginfo__bindgen_ty_1__bindgen_ty_6"]
        [::std::mem::size_of::<__siginfo__bindgen_ty_1__bindgen_ty_6>() - 40usize];
    ["Alignment of __siginfo__bindgen_ty_1__bindgen_ty_6"]
        [::std::mem::align_of::<__siginfo__bindgen_ty_1__bindgen_ty_6>() - 8usize];
    ["Offset of field: __siginfo__bindgen_ty_1__bindgen_ty_6::__spare1__"]
        [::std::mem::offset_of!(__siginfo__bindgen_ty_1__bindgen_ty_6, __spare1__) - 0usize];
    ["Offset of field: __siginfo__bindgen_ty_1__bindgen_ty_6::__spare2__"]
        [::std::mem::offset_of!(__siginfo__bindgen_ty_1__bindgen_ty_6, __spare2__) - 8usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __siginfo__bindgen_ty_1"][::std::mem::size_of::<__siginfo__bindgen_ty_1>() - 40usize];
    ["Alignment of __siginfo__bindgen_ty_1"]
        [::std::mem::align_of::<__siginfo__bindgen_ty_1>() - 8usize];
    ["Offset of field: __siginfo__bindgen_ty_1::_fault"]
        [::std::mem::offset_of!(__siginfo__bindgen_ty_1, _fault) - 0usize];
    ["Offset of field: __siginfo__bindgen_ty_1::_timer"]
        [::std::mem::offset_of!(__siginfo__bindgen_ty_1, _timer) - 0usize];
    ["Offset of field: __siginfo__bindgen_ty_1::_mesgq"]
        [::std::mem::offset_of!(__siginfo__bindgen_ty_1, _mesgq) - 0usize];
    ["Offset of field: __siginfo__bindgen_ty_1::_poll"]
        [::std::mem::offset_of!(__siginfo__bindgen_ty_1, _poll) - 0usize];
    ["Offset of field: __siginfo__bindgen_ty_1::_capsicum"]
        [::std::mem::offset_of!(__siginfo__bindgen_ty_1, _capsicum) - 0usize];
    ["Offset of field: __siginfo__bindgen_ty_1::__spare__"]
        [::std::mem::offset_of!(__siginfo__bindgen_ty_1, __spare__) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __siginfo"][::std::mem::size_of::<__siginfo>() - 80usize];
    ["Alignment of __siginfo"][::std::mem::align_of::<__siginfo>() - 8usize];
    ["Offset of field: __siginfo::si_signo"][::std::mem::offset_of!(__siginfo, si_signo) - 0usize];
    ["Offset of field: __siginfo::si_errno"][::std::mem::offset_of!(__siginfo, si_errno) - 4usize];
    ["Offset of field: __siginfo::si_code"][::std::mem::offset_of!(__siginfo, si_code) - 8usize];
    ["Offset of field: __siginfo::si_pid"][::std::mem::offset_of!(__siginfo, si_pid) - 12usize];
    ["Offset of field: __siginfo::si_uid"][::std::mem::offset_of!(__siginfo, si_uid) - 16usize];
    ["Offset of field: __siginfo::si_status"]
        [::std::mem::offset_of!(__siginfo, si_status) - 20usize];
    ["Offset of field: __siginfo::si_addr"][::std::mem::offset_of!(__siginfo, si_addr) - 24usize];
    ["Offset of field: __siginfo::si_value"][::std::mem::offset_of!(__siginfo, si_value) - 32usize];
    ["Offset of field: __siginfo::_reason"][::std::mem::offset_of!(__siginfo, _reason) - 40usize];
};
pub type siginfo_t = __siginfo;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct sigaction {
    pub __sigaction_u: sigaction__bindgen_ty_1,
    pub sa_flags: ::std::os::raw::c_int,
    pub sa_mask: sigset_t,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union sigaction__bindgen_ty_1 {
    pub __sa_handler: ::std::option::Option<unsafe extern "C" fn(arg1: ::std::os::raw::c_int)>,
    pub __sa_sigaction: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: ::std::os::raw::c_int,
            arg2: *mut __siginfo,
            arg3: *mut ::std::os::raw::c_void,
        ),
    >,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of sigaction__bindgen_ty_1"][::std::mem::size_of::<sigaction__bindgen_ty_1>() - 8usize];
    ["Alignment of sigaction__bindgen_ty_1"]
        [::std::mem::align_of::<sigaction__bindgen_ty_1>() - 8usize];
    ["Offset of field: sigaction__bindgen_ty_1::__sa_handler"]
        [::std::mem::offset_of!(sigaction__bindgen_ty_1, __sa_handler) - 0usize];
    ["Offset of field: sigaction__bindgen_ty_1::__sa_sigaction"]
        [::std::mem::offset_of!(sigaction__bindgen_ty_1, __sa_sigaction) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of sigaction"][::std::mem::size_of::<sigaction>() - 32usize];
    ["Alignment of sigaction"][::std::mem::align_of::<sigaction>() - 8usize];
    ["Offset of field: sigaction::__sigaction_u"]
        [::std::mem::offset_of!(sigaction, __sigaction_u) - 0usize];
    ["Offset of field: sigaction::sa_flags"][::std::mem::offset_of!(sigaction, sa_flags) - 8usize];
    ["Offset of field: sigaction::sa_mask"][::std::mem::offset_of!(sigaction, sa_mask) - 12usize];
};
pub type sig_t = __sighandler_t;
pub type __siginfohandler_t = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: ::std::os::raw::c_int,
        arg2: *mut __siginfo,
        arg3: *mut ::std::os::raw::c_void,
    ),
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sigvec {
    pub sv_handler: __sighandler_t,
    pub sv_mask: ::std::os::raw::c_int,
    pub sv_flags: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of sigvec"][::std::mem::size_of::<sigvec>() - 16usize];
    ["Alignment of sigvec"][::std::mem::align_of::<sigvec>() - 8usize];
    ["Offset of field: sigvec::sv_handler"][::std::mem::offset_of!(sigvec, sv_handler) - 0usize];
    ["Offset of field: sigvec::sv_mask"][::std::mem::offset_of!(sigvec, sv_mask) - 8usize];
    ["Offset of field: sigvec::sv_flags"][::std::mem::offset_of!(sigvec, sv_flags) - 12usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sigstack {
    pub ss_sp: *mut ::std::os::raw::c_void,
    pub ss_onstack: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of sigstack"][::std::mem::size_of::<sigstack>() - 16usize];
    ["Alignment of sigstack"][::std::mem::align_of::<sigstack>() - 8usize];
    ["Offset of field: sigstack::ss_sp"][::std::mem::offset_of!(sigstack, ss_sp) - 0usize];
    ["Offset of field: sigstack::ss_onstack"]
        [::std::mem::offset_of!(sigstack, ss_onstack) - 8usize];
};
unsafe extern "C" {
    pub fn signal(arg1: ::std::os::raw::c_int, arg2: __sighandler_t) -> __sighandler_t;
}
pub type u_char = ::std::os::raw::c_uchar;
pub type u_short = ::std::os::raw::c_ushort;
pub type u_int = ::std::os::raw::c_uint;
pub type u_long = ::std::os::raw::c_ulong;
pub type ushort = ::std::os::raw::c_ushort;
pub type uint = ::std::os::raw::c_uint;
pub type intmax_t = __intmax_t;
pub type uintmax_t = __uintmax_t;
pub type u_int8_t = __uint8_t;
pub type u_int16_t = __uint16_t;
pub type u_int32_t = __uint32_t;
pub type u_int64_t = __uint64_t;
pub type u_quad_t = __uint64_t;
pub type quad_t = __int64_t;
pub type qaddr_t = *mut quad_t;
pub type caddr_t = *mut ::std::os::raw::c_char;
pub type c_caddr_t = *const ::std::os::raw::c_char;
pub type blksize_t = __blksize_t;
pub type cpuwhich_t = __cpuwhich_t;
pub type cpulevel_t = __cpulevel_t;
pub type cpusetid_t = __cpusetid_t;
pub type blkcnt_t = __blkcnt_t;
pub type clock_t = __clock_t;
pub type clockid_t = __clockid_t;
pub type critical_t = __critical_t;
pub type daddr_t = __daddr_t;
pub type dev_t = __dev_t;
pub type fflags_t = __fflags_t;
pub type fixpt_t = __fixpt_t;
pub type fsblkcnt_t = __fsblkcnt_t;
pub type fsfilcnt_t = __fsfilcnt_t;
pub type gid_t = __gid_t;
pub type in_addr_t = __uint32_t;
pub type in_port_t = __uint16_t;
pub type id_t = __id_t;
pub type ino_t = __ino_t;
pub type key_t = __key_t;
pub type lwpid_t = __lwpid_t;
pub type mode_t = __mode_t;
pub type accmode_t = __accmode_t;
pub type nlink_t = __nlink_t;
pub type off_t = __off_t;
pub type off64_t = __off64_t;
pub type pid_t = __pid_t;
pub type register_t = __register_t;
pub type rlim_t = __rlim_t;
pub type sbintime_t = __sbintime_t;
pub type segsz_t = __segsz_t;
pub type suseconds_t = __suseconds_t;
pub type timer_t = __timer_t;
pub type mqd_t = __mqd_t;
pub type u_register_t = __u_register_t;
pub type useconds_t = __useconds_t;
pub type cap_ioctl_t = ::std::os::raw::c_ulong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cap_rights {
    _unused: [u8; 0],
}
pub type cap_rights_t = cap_rights;
pub type kpaddr_t = __uint64_t;
pub type kvaddr_t = __uint64_t;
pub type ksize_t = __uint64_t;
pub type kssize_t = __int64_t;
pub type vm_offset_t = __vm_offset_t;
pub type vm_ooffset_t = __uint64_t;
pub type vm_paddr_t = __vm_paddr_t;
pub type vm_pindex_t = __uint64_t;
pub type vm_size_t = __vm_size_t;
pub type rman_res_t = __rman_res_t;
pub type syscallarg_t = __register_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct timeval {
    pub tv_sec: time_t,
    pub tv_usec: suseconds_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of timeval"][::std::mem::size_of::<timeval>() - 16usize];
    ["Alignment of timeval"][::std::mem::align_of::<timeval>() - 8usize];
    ["Offset of field: timeval::tv_sec"][::std::mem::offset_of!(timeval, tv_sec) - 0usize];
    ["Offset of field: timeval::tv_usec"][::std::mem::offset_of!(timeval, tv_usec) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct itimerspec {
    pub it_interval: timespec,
    pub it_value: timespec,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of itimerspec"][::std::mem::size_of::<itimerspec>() - 32usize];
    ["Alignment of itimerspec"][::std::mem::align_of::<itimerspec>() - 8usize];
    ["Offset of field: itimerspec::it_interval"]
        [::std::mem::offset_of!(itimerspec, it_interval) - 0usize];
    ["Offset of field: itimerspec::it_value"]
        [::std::mem::offset_of!(itimerspec, it_value) - 16usize];
};
pub type __fd_mask = ::std::os::raw::c_ulong;
pub type fd_mask = __fd_mask;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct fd_set {
    pub __fds_bits: [__fd_mask; 16usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of fd_set"][::std::mem::size_of::<fd_set>() - 128usize];
    ["Alignment of fd_set"][::std::mem::align_of::<fd_set>() - 8usize];
    ["Offset of field: fd_set::__fds_bits"][::std::mem::offset_of!(fd_set, __fds_bits) - 0usize];
};
unsafe extern "C" {
    pub fn pselect(
        arg1: ::std::os::raw::c_int,
        arg2: *mut fd_set,
        arg3: *mut fd_set,
        arg4: *mut fd_set,
        arg5: *const timespec,
        arg6: *const sigset_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn select(
        arg1: ::std::os::raw::c_int,
        arg2: *mut fd_set,
        arg3: *mut fd_set,
        arg4: *mut fd_set,
        arg5: *mut timeval,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn ftruncate(arg1: ::std::os::raw::c_int, arg2: off_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn lseek(arg1: ::std::os::raw::c_int, arg2: off_t, arg3: ::std::os::raw::c_int) -> off_t;
}
unsafe extern "C" {
    pub fn mmap(
        arg1: *mut ::std::os::raw::c_void,
        arg2: usize,
        arg3: ::std::os::raw::c_int,
        arg4: ::std::os::raw::c_int,
        arg5: ::std::os::raw::c_int,
        arg6: off_t,
    ) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn truncate(arg1: *const ::std::os::raw::c_char, arg2: off_t) -> ::std::os::raw::c_int;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct reg32 {
    pub r_fs: __uint32_t,
    pub r_es: __uint32_t,
    pub r_ds: __uint32_t,
    pub r_edi: __uint32_t,
    pub r_esi: __uint32_t,
    pub r_ebp: __uint32_t,
    pub r_isp: __uint32_t,
    pub r_ebx: __uint32_t,
    pub r_edx: __uint32_t,
    pub r_ecx: __uint32_t,
    pub r_eax: __uint32_t,
    pub r_trapno: __uint32_t,
    pub r_err: __uint32_t,
    pub r_eip: __uint32_t,
    pub r_cs: __uint32_t,
    pub r_eflags: __uint32_t,
    pub r_esp: __uint32_t,
    pub r_ss: __uint32_t,
    pub r_gs: __uint32_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of reg32"][::std::mem::size_of::<reg32>() - 76usize];
    ["Alignment of reg32"][::std::mem::align_of::<reg32>() - 4usize];
    ["Offset of field: reg32::r_fs"][::std::mem::offset_of!(reg32, r_fs) - 0usize];
    ["Offset of field: reg32::r_es"][::std::mem::offset_of!(reg32, r_es) - 4usize];
    ["Offset of field: reg32::r_ds"][::std::mem::offset_of!(reg32, r_ds) - 8usize];
    ["Offset of field: reg32::r_edi"][::std::mem::offset_of!(reg32, r_edi) - 12usize];
    ["Offset of field: reg32::r_esi"][::std::mem::offset_of!(reg32, r_esi) - 16usize];
    ["Offset of field: reg32::r_ebp"][::std::mem::offset_of!(reg32, r_ebp) - 20usize];
    ["Offset of field: reg32::r_isp"][::std::mem::offset_of!(reg32, r_isp) - 24usize];
    ["Offset of field: reg32::r_ebx"][::std::mem::offset_of!(reg32, r_ebx) - 28usize];
    ["Offset of field: reg32::r_edx"][::std::mem::offset_of!(reg32, r_edx) - 32usize];
    ["Offset of field: reg32::r_ecx"][::std::mem::offset_of!(reg32, r_ecx) - 36usize];
    ["Offset of field: reg32::r_eax"][::std::mem::offset_of!(reg32, r_eax) - 40usize];
    ["Offset of field: reg32::r_trapno"][::std::mem::offset_of!(reg32, r_trapno) - 44usize];
    ["Offset of field: reg32::r_err"][::std::mem::offset_of!(reg32, r_err) - 48usize];
    ["Offset of field: reg32::r_eip"][::std::mem::offset_of!(reg32, r_eip) - 52usize];
    ["Offset of field: reg32::r_cs"][::std::mem::offset_of!(reg32, r_cs) - 56usize];
    ["Offset of field: reg32::r_eflags"][::std::mem::offset_of!(reg32, r_eflags) - 60usize];
    ["Offset of field: reg32::r_esp"][::std::mem::offset_of!(reg32, r_esp) - 64usize];
    ["Offset of field: reg32::r_ss"][::std::mem::offset_of!(reg32, r_ss) - 68usize];
    ["Offset of field: reg32::r_gs"][::std::mem::offset_of!(reg32, r_gs) - 72usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct reg {
    pub r_r15: __int64_t,
    pub r_r14: __int64_t,
    pub r_r13: __int64_t,
    pub r_r12: __int64_t,
    pub r_r11: __int64_t,
    pub r_r10: __int64_t,
    pub r_r9: __int64_t,
    pub r_r8: __int64_t,
    pub r_rdi: __int64_t,
    pub r_rsi: __int64_t,
    pub r_rbp: __int64_t,
    pub r_rbx: __int64_t,
    pub r_rdx: __int64_t,
    pub r_rcx: __int64_t,
    pub r_rax: __int64_t,
    pub r_trapno: __uint32_t,
    pub r_fs: __uint16_t,
    pub r_gs: __uint16_t,
    pub r_err: __uint32_t,
    pub r_es: __uint16_t,
    pub r_ds: __uint16_t,
    pub r_rip: __int64_t,
    pub r_cs: __int64_t,
    pub r_rflags: __int64_t,
    pub r_rsp: __int64_t,
    pub r_ss: __int64_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of reg"][::std::mem::size_of::<reg>() - 176usize];
    ["Alignment of reg"][::std::mem::align_of::<reg>() - 8usize];
    ["Offset of field: reg::r_r15"][::std::mem::offset_of!(reg, r_r15) - 0usize];
    ["Offset of field: reg::r_r14"][::std::mem::offset_of!(reg, r_r14) - 8usize];
    ["Offset of field: reg::r_r13"][::std::mem::offset_of!(reg, r_r13) - 16usize];
    ["Offset of field: reg::r_r12"][::std::mem::offset_of!(reg, r_r12) - 24usize];
    ["Offset of field: reg::r_r11"][::std::mem::offset_of!(reg, r_r11) - 32usize];
    ["Offset of field: reg::r_r10"][::std::mem::offset_of!(reg, r_r10) - 40usize];
    ["Offset of field: reg::r_r9"][::std::mem::offset_of!(reg, r_r9) - 48usize];
    ["Offset of field: reg::r_r8"][::std::mem::offset_of!(reg, r_r8) - 56usize];
    ["Offset of field: reg::r_rdi"][::std::mem::offset_of!(reg, r_rdi) - 64usize];
    ["Offset of field: reg::r_rsi"][::std::mem::offset_of!(reg, r_rsi) - 72usize];
    ["Offset of field: reg::r_rbp"][::std::mem::offset_of!(reg, r_rbp) - 80usize];
    ["Offset of field: reg::r_rbx"][::std::mem::offset_of!(reg, r_rbx) - 88usize];
    ["Offset of field: reg::r_rdx"][::std::mem::offset_of!(reg, r_rdx) - 96usize];
    ["Offset of field: reg::r_rcx"][::std::mem::offset_of!(reg, r_rcx) - 104usize];
    ["Offset of field: reg::r_rax"][::std::mem::offset_of!(reg, r_rax) - 112usize];
    ["Offset of field: reg::r_trapno"][::std::mem::offset_of!(reg, r_trapno) - 120usize];
    ["Offset of field: reg::r_fs"][::std::mem::offset_of!(reg, r_fs) - 124usize];
    ["Offset of field: reg::r_gs"][::std::mem::offset_of!(reg, r_gs) - 126usize];
    ["Offset of field: reg::r_err"][::std::mem::offset_of!(reg, r_err) - 128usize];
    ["Offset of field: reg::r_es"][::std::mem::offset_of!(reg, r_es) - 132usize];
    ["Offset of field: reg::r_ds"][::std::mem::offset_of!(reg, r_ds) - 134usize];
    ["Offset of field: reg::r_rip"][::std::mem::offset_of!(reg, r_rip) - 136usize];
    ["Offset of field: reg::r_cs"][::std::mem::offset_of!(reg, r_cs) - 144usize];
    ["Offset of field: reg::r_rflags"][::std::mem::offset_of!(reg, r_rflags) - 152usize];
    ["Offset of field: reg::r_rsp"][::std::mem::offset_of!(reg, r_rsp) - 160usize];
    ["Offset of field: reg::r_ss"][::std::mem::offset_of!(reg, r_ss) - 168usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct fpreg32 {
    pub fpr_env: [__uint32_t; 7usize],
    pub fpr_acc: [[__uint8_t; 10usize]; 8usize],
    pub fpr_ex_sw: __uint32_t,
    pub fpr_pad: [__uint8_t; 64usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of fpreg32"][::std::mem::size_of::<fpreg32>() - 176usize];
    ["Alignment of fpreg32"][::std::mem::align_of::<fpreg32>() - 4usize];
    ["Offset of field: fpreg32::fpr_env"][::std::mem::offset_of!(fpreg32, fpr_env) - 0usize];
    ["Offset of field: fpreg32::fpr_acc"][::std::mem::offset_of!(fpreg32, fpr_acc) - 28usize];
    ["Offset of field: fpreg32::fpr_ex_sw"][::std::mem::offset_of!(fpreg32, fpr_ex_sw) - 108usize];
    ["Offset of field: fpreg32::fpr_pad"][::std::mem::offset_of!(fpreg32, fpr_pad) - 112usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct fpreg {
    pub fpr_env: [__uint64_t; 4usize],
    pub fpr_acc: [[__uint8_t; 16usize]; 8usize],
    pub fpr_xacc: [[__uint8_t; 16usize]; 16usize],
    pub fpr_spare: [__uint64_t; 12usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of fpreg"][::std::mem::size_of::<fpreg>() - 512usize];
    ["Alignment of fpreg"][::std::mem::align_of::<fpreg>() - 8usize];
    ["Offset of field: fpreg::fpr_env"][::std::mem::offset_of!(fpreg, fpr_env) - 0usize];
    ["Offset of field: fpreg::fpr_acc"][::std::mem::offset_of!(fpreg, fpr_acc) - 32usize];
    ["Offset of field: fpreg::fpr_xacc"][::std::mem::offset_of!(fpreg, fpr_xacc) - 160usize];
    ["Offset of field: fpreg::fpr_spare"][::std::mem::offset_of!(fpreg, fpr_spare) - 416usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct xmmreg {
    pub xmm_env: [__uint32_t; 8usize],
    pub xmm_acc: [[__uint8_t; 16usize]; 8usize],
    pub xmm_reg: [[__uint8_t; 16usize]; 8usize],
    pub xmm_pad: [__uint8_t; 224usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of xmmreg"][::std::mem::size_of::<xmmreg>() - 512usize];
    ["Alignment of xmmreg"][::std::mem::align_of::<xmmreg>() - 4usize];
    ["Offset of field: xmmreg::xmm_env"][::std::mem::offset_of!(xmmreg, xmm_env) - 0usize];
    ["Offset of field: xmmreg::xmm_acc"][::std::mem::offset_of!(xmmreg, xmm_acc) - 32usize];
    ["Offset of field: xmmreg::xmm_reg"][::std::mem::offset_of!(xmmreg, xmm_reg) - 160usize];
    ["Offset of field: xmmreg::xmm_pad"][::std::mem::offset_of!(xmmreg, xmm_pad) - 288usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct dbreg32 {
    pub dr: [__uint32_t; 8usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of dbreg32"][::std::mem::size_of::<dbreg32>() - 32usize];
    ["Alignment of dbreg32"][::std::mem::align_of::<dbreg32>() - 4usize];
    ["Offset of field: dbreg32::dr"][::std::mem::offset_of!(dbreg32, dr) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct dbreg {
    pub dr: [__uint64_t; 16usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of dbreg"][::std::mem::size_of::<dbreg>() - 128usize];
    ["Alignment of dbreg"][::std::mem::align_of::<dbreg>() - 8usize];
    ["Offset of field: dbreg::dr"][::std::mem::offset_of!(dbreg, dr) - 0usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct segbasereg32 {
    pub r_fsbase: __uint32_t,
    pub r_gsbase: __uint32_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of segbasereg32"][::std::mem::size_of::<segbasereg32>() - 8usize];
    ["Alignment of segbasereg32"][::std::mem::align_of::<segbasereg32>() - 4usize];
    ["Offset of field: segbasereg32::r_fsbase"]
        [::std::mem::offset_of!(segbasereg32, r_fsbase) - 0usize];
    ["Offset of field: segbasereg32::r_gsbase"]
        [::std::mem::offset_of!(segbasereg32, r_gsbase) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct segbasereg {
    pub r_fsbase: __uint64_t,
    pub r_gsbase: __uint64_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of segbasereg"][::std::mem::size_of::<segbasereg>() - 16usize];
    ["Alignment of segbasereg"][::std::mem::align_of::<segbasereg>() - 8usize];
    ["Offset of field: segbasereg::r_fsbase"]
        [::std::mem::offset_of!(segbasereg, r_fsbase) - 0usize];
    ["Offset of field: segbasereg::r_gsbase"]
        [::std::mem::offset_of!(segbasereg, r_gsbase) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ptrace_xstate_info {
    pub xsave_mask: u64,
    pub xsave_len: u32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ptrace_xstate_info"][::std::mem::size_of::<ptrace_xstate_info>() - 16usize];
    ["Alignment of ptrace_xstate_info"][::std::mem::align_of::<ptrace_xstate_info>() - 8usize];
    ["Offset of field: ptrace_xstate_info::xsave_mask"]
        [::std::mem::offset_of!(ptrace_xstate_info, xsave_mask) - 0usize];
    ["Offset of field: ptrace_xstate_info::xsave_len"]
        [::std::mem::offset_of!(ptrace_xstate_info, xsave_len) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ptrace_io_desc {
    pub piod_op: ::std::os::raw::c_int,
    pub piod_offs: *mut ::std::os::raw::c_void,
    pub piod_addr: *mut ::std::os::raw::c_void,
    pub piod_len: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ptrace_io_desc"][::std::mem::size_of::<ptrace_io_desc>() - 32usize];
    ["Alignment of ptrace_io_desc"][::std::mem::align_of::<ptrace_io_desc>() - 8usize];
    ["Offset of field: ptrace_io_desc::piod_op"]
        [::std::mem::offset_of!(ptrace_io_desc, piod_op) - 0usize];
    ["Offset of field: ptrace_io_desc::piod_offs"]
        [::std::mem::offset_of!(ptrace_io_desc, piod_offs) - 8usize];
    ["Offset of field: ptrace_io_desc::piod_addr"]
        [::std::mem::offset_of!(ptrace_io_desc, piod_addr) - 16usize];
    ["Offset of field: ptrace_io_desc::piod_len"]
        [::std::mem::offset_of!(ptrace_io_desc, piod_len) - 24usize];
};
#[repr(C)]
#[derive(Copy, Clone)]
pub struct ptrace_lwpinfo {
    pub pl_lwpid: lwpid_t,
    pub pl_event: ::std::os::raw::c_int,
    pub pl_flags: ::std::os::raw::c_int,
    pub pl_sigmask: sigset_t,
    pub pl_siglist: sigset_t,
    pub pl_siginfo: __siginfo,
    pub pl_tdname: [::std::os::raw::c_char; 20usize],
    pub pl_child_pid: pid_t,
    pub pl_syscall_code: u_int,
    pub pl_syscall_narg: u_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ptrace_lwpinfo"][::std::mem::size_of::<ptrace_lwpinfo>() - 160usize];
    ["Alignment of ptrace_lwpinfo"][::std::mem::align_of::<ptrace_lwpinfo>() - 8usize];
    ["Offset of field: ptrace_lwpinfo::pl_lwpid"]
        [::std::mem::offset_of!(ptrace_lwpinfo, pl_lwpid) - 0usize];
    ["Offset of field: ptrace_lwpinfo::pl_event"]
        [::std::mem::offset_of!(ptrace_lwpinfo, pl_event) - 4usize];
    ["Offset of field: ptrace_lwpinfo::pl_flags"]
        [::std::mem::offset_of!(ptrace_lwpinfo, pl_flags) - 8usize];
    ["Offset of field: ptrace_lwpinfo::pl_sigmask"]
        [::std::mem::offset_of!(ptrace_lwpinfo, pl_sigmask) - 12usize];
    ["Offset of field: ptrace_lwpinfo::pl_siglist"]
        [::std::mem::offset_of!(ptrace_lwpinfo, pl_siglist) - 28usize];
    ["Offset of field: ptrace_lwpinfo::pl_siginfo"]
        [::std::mem::offset_of!(ptrace_lwpinfo, pl_siginfo) - 48usize];
    ["Offset of field: ptrace_lwpinfo::pl_tdname"]
        [::std::mem::offset_of!(ptrace_lwpinfo, pl_tdname) - 128usize];
    ["Offset of field: ptrace_lwpinfo::pl_child_pid"]
        [::std::mem::offset_of!(ptrace_lwpinfo, pl_child_pid) - 148usize];
    ["Offset of field: ptrace_lwpinfo::pl_syscall_code"]
        [::std::mem::offset_of!(ptrace_lwpinfo, pl_syscall_code) - 152usize];
    ["Offset of field: ptrace_lwpinfo::pl_syscall_narg"]
        [::std::mem::offset_of!(ptrace_lwpinfo, pl_syscall_narg) - 156usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ptrace_sc_ret {
    pub sr_retval: [syscallarg_t; 2usize],
    pub sr_error: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ptrace_sc_ret"][::std::mem::size_of::<ptrace_sc_ret>() - 24usize];
    ["Alignment of ptrace_sc_ret"][::std::mem::align_of::<ptrace_sc_ret>() - 8usize];
    ["Offset of field: ptrace_sc_ret::sr_retval"]
        [::std::mem::offset_of!(ptrace_sc_ret, sr_retval) - 0usize];
    ["Offset of field: ptrace_sc_ret::sr_error"]
        [::std::mem::offset_of!(ptrace_sc_ret, sr_error) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ptrace_vm_entry {
    pub pve_entry: ::std::os::raw::c_int,
    pub pve_timestamp: ::std::os::raw::c_int,
    pub pve_start: u_long,
    pub pve_end: u_long,
    pub pve_offset: u_long,
    pub pve_prot: u_int,
    pub pve_pathlen: u_int,
    pub pve_fileid: ::std::os::raw::c_long,
    pub pve_fsid: u32,
    pub pve_path: *mut ::std::os::raw::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ptrace_vm_entry"][::std::mem::size_of::<ptrace_vm_entry>() - 64usize];
    ["Alignment of ptrace_vm_entry"][::std::mem::align_of::<ptrace_vm_entry>() - 8usize];
    ["Offset of field: ptrace_vm_entry::pve_entry"]
        [::std::mem::offset_of!(ptrace_vm_entry, pve_entry) - 0usize];
    ["Offset of field: ptrace_vm_entry::pve_timestamp"]
        [::std::mem::offset_of!(ptrace_vm_entry, pve_timestamp) - 4usize];
    ["Offset of field: ptrace_vm_entry::pve_start"]
        [::std::mem::offset_of!(ptrace_vm_entry, pve_start) - 8usize];
    ["Offset of field: ptrace_vm_entry::pve_end"]
        [::std::mem::offset_of!(ptrace_vm_entry, pve_end) - 16usize];
    ["Offset of field: ptrace_vm_entry::pve_offset"]
        [::std::mem::offset_of!(ptrace_vm_entry, pve_offset) - 24usize];
    ["Offset of field: ptrace_vm_entry::pve_prot"]
        [::std::mem::offset_of!(ptrace_vm_entry, pve_prot) - 32usize];
    ["Offset of field: ptrace_vm_entry::pve_pathlen"]
        [::std::mem::offset_of!(ptrace_vm_entry, pve_pathlen) - 36usize];
    ["Offset of field: ptrace_vm_entry::pve_fileid"]
        [::std::mem::offset_of!(ptrace_vm_entry, pve_fileid) - 40usize];
    ["Offset of field: ptrace_vm_entry::pve_fsid"]
        [::std::mem::offset_of!(ptrace_vm_entry, pve_fsid) - 48usize];
    ["Offset of field: ptrace_vm_entry::pve_path"]
        [::std::mem::offset_of!(ptrace_vm_entry, pve_path) - 56usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ptrace_coredump {
    pub pc_fd: ::std::os::raw::c_int,
    pub pc_flags: u32,
    pub pc_limit: off_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ptrace_coredump"][::std::mem::size_of::<ptrace_coredump>() - 16usize];
    ["Alignment of ptrace_coredump"][::std::mem::align_of::<ptrace_coredump>() - 8usize];
    ["Offset of field: ptrace_coredump::pc_fd"]
        [::std::mem::offset_of!(ptrace_coredump, pc_fd) - 0usize];
    ["Offset of field: ptrace_coredump::pc_flags"]
        [::std::mem::offset_of!(ptrace_coredump, pc_flags) - 4usize];
    ["Offset of field: ptrace_coredump::pc_limit"]
        [::std::mem::offset_of!(ptrace_coredump, pc_limit) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ptrace_sc_remote {
    pub pscr_ret: ptrace_sc_ret,
    pub pscr_syscall: u_int,
    pub pscr_nargs: u_int,
    pub pscr_args: *mut syscallarg_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ptrace_sc_remote"][::std::mem::size_of::<ptrace_sc_remote>() - 40usize];
    ["Alignment of ptrace_sc_remote"][::std::mem::align_of::<ptrace_sc_remote>() - 8usize];
    ["Offset of field: ptrace_sc_remote::pscr_ret"]
        [::std::mem::offset_of!(ptrace_sc_remote, pscr_ret) - 0usize];
    ["Offset of field: ptrace_sc_remote::pscr_syscall"]
        [::std::mem::offset_of!(ptrace_sc_remote, pscr_syscall) - 24usize];
    ["Offset of field: ptrace_sc_remote::pscr_nargs"]
        [::std::mem::offset_of!(ptrace_sc_remote, pscr_nargs) - 28usize];
    ["Offset of field: ptrace_sc_remote::pscr_args"]
        [::std::mem::offset_of!(ptrace_sc_remote, pscr_args) - 32usize];
};
unsafe extern "C" {
    pub fn ptrace(
        _request: ::std::os::raw::c_int,
        _pid: pid_t,
        _addr: caddr_t,
        _data: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
pub type __builtin_va_list = [__va_list_tag; 1usize];
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __va_list_tag {
    pub gp_offset: ::std::os::raw::c_uint,
    pub fp_offset: ::std::os::raw::c_uint,
    pub overflow_arg_area: *mut ::std::os::raw::c_void,
    pub reg_save_area: *mut ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of __va_list_tag"][::std::mem::size_of::<__va_list_tag>() - 24usize];
    ["Alignment of __va_list_tag"][::std::mem::align_of::<__va_list_tag>() - 8usize];
    ["Offset of field: __va_list_tag::gp_offset"]
        [::std::mem::offset_of!(__va_list_tag, gp_offset) - 0usize];
    ["Offset of field: __va_list_tag::fp_offset"]
        [::std::mem::offset_of!(__va_list_tag, fp_offset) - 4usize];
    ["Offset of field: __va_list_tag::overflow_arg_area"]
        [::std::mem::offset_of!(__va_list_tag, overflow_arg_area) - 8usize];
    ["Offset of field: __va_list_tag::reg_save_area"]
        [::std::mem::offset_of!(__va_list_tag, reg_save_area) - 16usize];
};
